server:
  port: 10003
  servlet:
    context-path:
spring:
  servlet:
    ##设置文件上传
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  redis:
#    port: 6379
#    host: 129.28.198.241
#    timeout: 0  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    password: z123456
    sentinel:
      master: mymaster
      nodes: 192.168.56.101:26379,192.168.56.102:26379,192.168.56.103:26379
  #mysql数据库配置,连接池为druid
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://129.28.198.241:3306/routes?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: zb
    password: z123456

  ##必须写明方言,和jpa使用类型,不然发生错误
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect
  task:
    execution:
      pool:
        core-size: 50
        max-size: 100
        keep-alive: 60s
        allow-core-thread-timeout: true
        queue-capacity: 50
      thread-name-prefix: zb_
      shutdown:
        await-termination: true
        await-termination-period: 60


#日志
logging:
  config: classpath:logback.xml
