server:
  port: 10003
  servlet:
    context-path:
spring:
  redis:
#    port: 6379
#    host: 129.28.198.241
#    timeout: 0  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    password: z123456
    sentinel:
      master: mymaster
      nodes: 192.168.56.101:26379,192.168.56.102:26379,192.168.56.103:26379
#线程池设置
  task:
    execution:
      pool:
        core-size: 50
        max-size: 100
        keep-alive: 60s
        allow-core-thread-timeout: true
        queue-capacity: 50
      thread-name-prefix: zb_
      shutdown:
        await-termination: true
        await-termination-period: 60


#日志
logging:
  config: classpath:logback.xml
